'''


'''
from PyQt5 import QtCore as qtc
from PyQt5 import QtGui as qtg
from PyQt5 import QtWidgets as qtw
import sys
# import the UI classes generated by pyuic5
from Window1 import Ui_MainWindow as Ui_MainWindow1
from Window2 import Ui_SecondWindow as Ui_MainWindow2
# from Window3 import Ui_ThirdWindow as Ui_MainWindow3
from Window4_Dialog import Ui_Dialog as Ui_MainWindow3


# Define a proper Main Window class to encapsulate logic
class MainWindow(qtw.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.open_second_window)  # Connect pushButton to open second window
        self.statusBar=self.ui.statusbar
        self.statusBar.showMessage("Welcome to the Main Window")  # Set initial status bar message
        self.statusBar.setStyleSheet("background-color: lightgray;")  # Set status bar style
    def open_second_window(self):
        # Create a new QMainWindow and apply the Ui_SecondWindow layout to it
        self.second_window = qtw.QMainWindow()  # This is a real window
        self.second_ui = Ui_MainWindow2()       # This is the layout/setup
        self.second_ui.setupUi(self.second_window)
        self.second_ui.pushButton.clicked.connect(self.open_third_window)  # connect second window's button
        
        self.menubar =self.second_ui.menubar
        self.menubar.setStyleSheet("background-color: lightblue;")
        self.statusbar = self.second_ui.statusbar
        self.statusbar.setStyleSheet("background-color: lightgreen;")
        self.second_window.show()  # Now it can be shown!

    # def open_third_window(self):        ##  Use the new ThirdDialog class, leftover from previous example Window_Import2.py
    #     self.third_window = ThirdDialog(self)  # Use your new class
    #     self.third_window.exec_()  # Modal dialog

    def open_third_window(self):
        dialog = ThirdDialog(self)
        if dialog.exec_() == qtw.QDialog.Accepted:
            # Dialog was accepted: use returned_name
            name = dialog.returned_name
            self.statusbar.showMessage(f"User entered: {name}")
        else:
            self.statusbar.showMessage("Dialog canceled.")


    # def open_third_window(self):
    #     # Create a new QDialog  and apply the Ui_ThirdWindow layout to it
    #     self.third_window = qtw.QDialog()  # Using QDialog for the third window
    #     self.third_window.setWindowTitle("Third Window")
    #     self.third_ui = Ui_MainWindow3()
    #     self.third_ui.setupUi(self.third_window)
    #     self.third_ui.label.setText("Welcome to the Third Window!")
    #     self.third_ui.buttonBox.accepted.connect(self.third_window.accept)  # Connect buttonBox to accept
    #     self.third_ui.buttonBox.rejected.connect(self.third_window.reject)  # Connect buttonBox to reject
    #     self.third_window.exec_()  # Open modally (blocks other windows until closed)
        
        
        
    #     # OR use: self.third_window.show() for non-modal
    #     # Open modally (blocks other windows until closed)
    # def open_third_window(self): ## use this with a third window as a QDialog: Codemy/Cod_24_SecondWindow/Codemy_SecondWindow/Window4_Dialog.py
    #     self.third_window = qtw.QDialog(self)  # ✅ Create a QDialog instance, not QMainWindow
    #     self.third_ui = Ui_MainWindow3()       # ✅ This is your Ui_Dialog
    #     self.third_ui.setupUi(self.third_window)  # ✅ Apply the dialog layout to the dialog
    #     self.third_window.exec_()  # ✅ Open modally (blocks other windows until closed)
    #     # OR use: self.third_window.show() for non-modal

    
    
    # def open_third_window(self): ## use this if you want a third window as a QMainWindow :Codemy/Cod_24_SecondWindow/Codemy_SecondWindow/Window3.py
    #     # Create a new QMainWindow and apply the Ui_ThirdWindow layout to it
    #     self.third_window = qtw.QMainWindow()
    #     self.third_ui = Ui_MainWindow3()
    #     self.third_ui.setupUi(self.third_window)
    #     self.third_window.show()

from PyQt5 import QtWidgets as qtw, QtCore as qtc, QtGui as qtg
from Window4_Dialog import Ui_Dialog  # This is your pyuic5-generated dialog UI class

class ThirdDialog(qtw.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)  # Initialize the QDialog with an optional parent
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)  # Set up the UI on this dialog

        # Example: Customize or connect signals here
        self.ui.label.setText("Welcome to the Third Window!")

        # You can connect button signals manually if needed
        self.ui.buttonBox.accepted.connect(self.accept_dialog)
        self.ui.buttonBox.rejected.connect(self.reject_dialog)

    def accept_dialog(self):
        print("Dialog accepted")
        self.ui.label.setText("Dialog Accepted!")  # Example of changing label text
        # You can add more logic here if needed
        # For example, you might want to close the dialog or perform some action
        self.accept()  # Close the dialog with Accepted result

    def reject_dialog(self):
        print("Dialog rejected")
        self.ui.label.setText("Dialog Rejected!")
        # You can add more logic here if needed
        self.reject()  # Close the dialog with Rejected result

    
    
if __name__ == "__main__":
    import sys
    app = qtw.QApplication(sys.argv)
    main_win = MainWindow()  # Instantiate the class-based main window
    main_win.show()  # Show the main window
    sys.exit(app.exec_())

